const ADD_TRANSACTION = 'ADD_TRANSACTION',
  SEND_NEW_TRANSACTION = 'SEND_NEW_TRANSACTION',
  SUCCESSFUL_NEW_TRANSACTION = 'SUCCESSFUL_NEW_TRANSACTION',
  FAILED_NEW_TRANSACTION = 'FAILED_NEW_TRANSACTION',

  GET_TRANSACTIONS = 'GET_TRANSACTIONS',
  REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS',
  RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS',
  FAILED_RECEIVED_TRANSACTIONS = 'FAILED_RECEIVED_TRANSACTIONS',

  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  SEND_UPDATED_TRANSACTION = 'SEND_UPDATED_TRANSACTION',
  SUCCESSFUL_UPDATED_TRANSACTION = 'SUCCESSFUL_UPDATED_TRANSACTION',
  FAILED_UPDATED_TRANSACTION = 'FAILED_UPDATED_TRANSACTION',

  DELETE_TRANSACTION = 'DELETE_TRANSACTION',
  SEND_DELETED_TRANSACTION = 'SEND_DELETED_TRANSACTION',
  SUCCESSFUL_DELETED_TRANSACTION = 'SUCCESSFUL_DELETED_TRANSACTION',
  FAILED_DELETED_TRANSACTION = 'FAILED_DELETED_TRANSACTION'


const GET_ACCOUNTS = 'GET_ACCOUNTS',
  REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS',
  RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS',
  FAILED_RECEIVED_ACCOUNTS = 'FAILED_RECEIVED_ACCOUNTS'


const CREATE_GOAL = 'CREATE_GOAL',
  SEND_NEW_GOAL = 'SEND_NEW_GOAL',
  SUCCESSFUL_NEW_GOAL = 'SUCCESSFUL_NEW_GOAL',
  FAILED_NEW_GOAL = 'FAILED_NEW_GOAL',

  GET_GOALS = 'GET_GOALS',
  REQUEST_GOALS = 'REQUEST_GOALS',
  RECEIVE_GOALS = 'RECEIVE_GOALS',
  FAILED_RECEIVED_GOALS = 'FAILED_RECEIVED_GOALS',

  CHANGE_GOAL = 'CHANGE_GOAL',
  SEND_UPDATED_GOAL = 'SEND_UPDATED_GOAL',
  SUCCESSFUL_UPDATED_GOAL = 'SUCCESSFUL_UPDATED_GOAL',
  FAILED_UPDATED_GOAL = 'FAILED_UPDATED_GOAL',

  DELETE_GOAL = 'DELETE_GOAL',
  SEND_DELETED_GOAL = 'SEND_DELETED_GOAL',
  SUCCESSFUL_DELETED_GOAL = 'SUCCESSFUL_DELETED_GOAL',
  FAILED_DELETED_GOAL = 'FAILED_DELETED_GOAL'


const CREATE_BILL = 'CREATE_BILL',
  SEND_NEW_BILL = 'SEND_NEW_BILL',
  SUCCESSFUL_NEW_BILL = 'SUCCESSFUL_NEW_BILL',
  FAILED_NEW_BILL = 'FAILED_NEW_BILL',

  GET_BILLS = 'GET_BILLS',
  REQUEST_BILLS = 'REQUEST_BILLS',
  RECEIVE_BILLS = 'RECEIVE_BILLS',
  FAILED_RECEIVED_BILLS = 'FAILED_RECEIVED_BILLS',

  CHANGE_BILL = 'CHANGE_BILL',
  SEND_UPDATED_BILL = 'SEND_UPDATED_BILL',
  SUCCESSFUL_UPDATED_BILL = 'SUCCESSFUL_UPDATED_BILL',
  FAILED_UPDATED_BILL = 'FAILED_UPDATED_BILL',

  DELETE_BILL = 'DELETE_BILL',
  SEND_DELETED_BILL = 'SEND_DELETED_BILL',
  SUCCESSFUL_DELETED_BILL = 'SUCCESSFUL_DELETED_BILL',
  FAILED_DELETED_BILL = 'FAILED_DELETED_BILL'

export {
  ADD_TRANSACTION, SEND_NEW_TRANSACTION, SUCCESSFUL_NEW_TRANSACTION, FAILED_NEW_TRANSACTION,
  GET_TRANSACTIONS, REQUEST_TRANSACTIONS, RECEIVE_TRANSACTIONS, FAILED_RECEIVED_TRANSACTIONS,
  UPDATE_TRANSACTION, SEND_UPDATED_TRANSACTION, SUCCESSFUL_UPDATED_TRANSACTION, FAILED_UPDATED_TRANSACTION,
  DELETE_TRANSACTION, SEND_DELETED_TRANSACTION, SUCCESSFUL_DELETED_TRANSACTION, FAILED_DELETED_TRANSACTION,
  GET_ACCOUNTS, REQUEST_ACCOUNTS, RECEIVE_ACCOUNTS, FAILED_RECEIVED_ACCOUNTS,
  CREATE_GOAL, SEND_NEW_GOAL, SUCCESSFUL_NEW_GOAL, FAILED_NEW_GOAL,
  GET_GOALS, REQUEST_GOALS, RECEIVE_GOALS, FAILED_RECEIVED_GOALS,
  CHANGE_GOAL, SEND_UPDATED_GOAL, SUCCESSFUL_UPDATED_GOAL, FAILED_UPDATED_GOAL,
  DELETE_GOAL, SEND_DELETED_GOAL, SUCCESSFUL_DELETED_GOAL, FAILED_DELETED_GOAL,
  CREATE_BILL, SEND_NEW_BILL, SUCCESSFUL_NEW_BILL, FAILED_NEW_BILL,
  GET_BILLS, REQUEST_BILLS, RECEIVE_BILLS, FAILED_RECEIVED_BILLS,
  CHANGE_BILL, SEND_UPDATED_BILL, SUCCESSFUL_UPDATED_BILL, FAILED_UPDATED_BILL,
  DELETE_BILL, SEND_DELETED_BILL, SUCCESSFUL_DELETED_BILL, FAILED_DELETED_BILL
}
