const ADD_TRANSACTION = 'ADD_TRANSACTION'
const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'

const GET_ACCOUNTS = 'GET_ACCOUNTS'

const CREATE_GOAL = 'CREATE_GOAL'
const GET_GOALS = 'GET_GOALS'
const CHANGE_GOAL = 'CHANGE_GOAL'
const DELETE_GOAL = 'DELETE_GOAL'

const CREATE_BILL = 'CREATE_BILL'
const GET_BILLS = 'GET_BILLS'
const CHANGE_BILL = 'CHANGE_BILL'
const DELETE_BILL = 'DELETE_BILL'

export { ADD_TRANSACTION, GET_TRANSACTIONS, UPDATE_TRANSACTION, GET_ACCOUNTS, CREATE_GOAL, GET_GOALS, CHANGE_GOAL, DELETE_GOAL, CREATE_BILL, GET_BILLS, CHANGE_BILL, DELETE_BILL }
