const ADD_TRANSACTION = 'ADD_TRANSACTION'
const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS'
const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS'
const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'

const GET_ACCOUNTS = 'GET_ACCOUNTS'
const REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS'
const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS'

const CREATE_GOAL = 'CREATE_GOAL'
const GET_GOALS = 'GET_GOALS'
const REQUEST_GOALS = 'REQUEST_GOALS'
const RECEIVE_GOALS = 'RECEIVE_GOALS'
const CHANGE_GOAL = 'CHANGE_GOAL'
const DELETE_GOAL = 'DELETE_GOAL'

const CREATE_BILL = 'CREATE_BILL'
const GET_BILLS = 'GET_BILLS'
const REQUEST_BILLS = 'REQUEST_BILLS'
const RECEIVE_BILLS = 'RECEIVE_BILLS'
const CHANGE_BILL = 'CHANGE_BILL'
const DELETE_BILL = 'DELETE_BILL'

export { ADD_TRANSACTION, GET_TRANSACTIONS, REQUEST_TRANSACTIONS, RECEIVE_TRANSACTIONS, UPDATE_TRANSACTION, GET_ACCOUNTS, REQUEST_ACCOUNTS, RECEIVE_ACCOUNTS, CREATE_GOAL, GET_GOALS, REQUEST_GOALS, RECEIVE_GOALS, CHANGE_GOAL, DELETE_GOAL, CREATE_BILL, GET_BILLS, REQUEST_BILLS, RECEIVE_BILLS, CHANGE_BILL, DELETE_BILL }
