const GET_ACCOUNTS = 'GET_ACCOUNTS',
  REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS',
  RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS',
  FAILED_RECEIVED_ACCOUNTS = 'FAILED_RECEIVED_ACCOUNTS'


export {
  GET_ACCOUNTS, REQUEST_ACCOUNTS, RECEIVE_ACCOUNTS, FAILED_RECEIVED_ACCOUNTS
}
