const SET_ACCOUNT_STATUSES = 'CHECK_ACCOUNT_STATUSES',
  GET_ACCOUNTS = 'GET_ACCOUNTS',
  REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS',
  RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS',
  FAILED_RECEIVED_ACCOUNTS = 'FAILED_RECEIVED_ACCOUNTS',

  EDIT_ACCOUNT = 'EDIT_ACCOUNT',
  UPDATE_ACCOUNT = 'UPDATE_ACCOUNT',
  CANCEL_EDIT_ACCOUNT = 'CANCEL_EDIT_ACCOUNT',
  SEND_UPDATED_ACCOUNT = 'SEND_UPDATED_ACCOUNT',
  SUCCESSFUL_UPDATED_ACCOUNT = 'SUCCESSFUL_UPDATED_ACCOUNT',
  FAILED_UPDATED_ACCOUNT = 'FAILED_UPDATED_ACCOUNT',
  MARK_ACCOUNT_ACCESSIBLE = 'MARK_ACCOUNT_ACCESSIBLE'


export {
  SET_ACCOUNT_STATUSES, GET_ACCOUNTS, REQUEST_ACCOUNTS, RECEIVE_ACCOUNTS, FAILED_RECEIVED_ACCOUNTS,
  EDIT_ACCOUNT, UPDATE_ACCOUNT, CANCEL_EDIT_ACCOUNT, SEND_UPDATED_ACCOUNT, SUCCESSFUL_UPDATED_ACCOUNT, FAILED_UPDATED_ACCOUNT,
  MARK_ACCOUNT_ACCESSIBLE
}
