const CREATE_BILL = 'CREATE_BILL',
  ADD_BILL = 'ADD_BILL',
  SEND_NEW_BILL = 'SEND_NEW_BILL',
  SUCCESSFUL_NEW_BILL = 'SUCCESSFUL_NEW_BILL',
  FAILED_NEW_BILL = 'FAILED_NEW_BILL',

  GET_BILLS = 'GET_BILLS',
  REQUEST_BILLS = 'REQUEST_BILLS',
  RECEIVE_BILLS = 'RECEIVE_BILLS',
  FAILED_RECEIVED_BILLS = 'FAILED_RECEIVED_BILLS',

  EDIT_BILL = 'EDIT_BILL',
  UPDATE_BILL = 'UPDATE_BILL',
  CANCEL_EDIT_BILL = 'CANCEL_EDIT_BILL',
  SEND_UPDATED_BILL = 'SEND_UPDATED_BILL',
  SUCCESSFUL_UPDATED_BILL = 'SUCCESSFUL_UPDATED_BILL',
  FAILED_UPDATED_BILL = 'FAILED_UPDATED_BILL',

  DELETE_BILL = 'DELETE_BILL',
  CONFIRM_DELETE_BILL = 'CONFIRM_DELETE_BILL',
  CANCEL_DELETE_BILL = 'CANCEL_DELETE_BILL',
  SEND_DELETED_BILL = 'SEND_DELETED_BILL',
  SUCCESSFUL_DELETED_BILL = 'SUCCESSFUL_DELETED_BILL',
  FAILED_DELETED_BILL = 'FAILED_DELETED_BILL'


export {
  CREATE_BILL, ADD_BILL, SEND_NEW_BILL, SUCCESSFUL_NEW_BILL, FAILED_NEW_BILL,
  GET_BILLS, REQUEST_BILLS, RECEIVE_BILLS, FAILED_RECEIVED_BILLS,
  EDIT_BILL, UPDATE_BILL, CANCEL_EDIT_BILL, SEND_UPDATED_BILL, SUCCESSFUL_UPDATED_BILL, FAILED_UPDATED_BILL,
  DELETE_BILL, CONFIRM_DELETE_BILL, CANCEL_DELETE_BILL, SEND_DELETED_BILL, SUCCESSFUL_DELETED_BILL, FAILED_DELETED_BILL
}
