const CREATE_GOAL = 'CREATE_GOAL',
  ADD_GOAL = 'ADD_GOAL',
  CANCEL_CREATE_GOAL = 'CANCEL_CREATE_GOAL',
  SEND_NEW_GOAL = 'SEND_NEW_GOAL',
  SUCCESSFUL_NEW_GOAL = 'SUCCESSFUL_NEW_GOAL',
  FAILED_NEW_GOAL = 'FAILED_NEW_GOAL',

  GET_GOALS = 'GET_GOALS',
  REQUEST_GOALS = 'REQUEST_GOALS',
  RECEIVE_GOALS = 'RECEIVE_GOALS',
  FAILED_RECEIVED_GOALS = 'FAILED_RECEIVED_GOALS',

  EDIT_GOAL = 'EDIT_GOAL',
  UPDATE_GOAL = 'UPDATE_GOAL',
  CANCEL_EDIT_GOAL = 'CANCEL_EDIT_GOAL',
  SEND_UPDATED_GOAL = 'SEND_UPDATED_GOAL',
  SUCCESSFUL_UPDATED_GOAL = 'SUCCESSFUL_UPDATED_GOAL',
  FAILED_UPDATED_GOAL = 'FAILED_UPDATED_GOAL',

  DELETE_GOAL = 'DELETE_GOAL',
  CONFIRM_DELETE_GOAL = 'CONFIRM_DELETE_GOAL',
  CANCEL_DELETE_GOAL = 'CANCEL_DELETE_GOAL',
  SEND_DELETED_GOAL = 'SEND_DELETED_GOAL',
  SUCCESSFUL_DELETED_GOAL = 'SUCCESSFUL_DELETED_GOAL',
  FAILED_DELETED_GOAL = 'FAILED_DELETED_GOAL'


export {
  CREATE_GOAL, CANCEL_CREATE_GOAL, ADD_GOAL, SEND_NEW_GOAL, SUCCESSFUL_NEW_GOAL, FAILED_NEW_GOAL,
  GET_GOALS, REQUEST_GOALS, RECEIVE_GOALS, FAILED_RECEIVED_GOALS,
  EDIT_GOAL, UPDATE_GOAL, CANCEL_EDIT_GOAL, SEND_UPDATED_GOAL, SUCCESSFUL_UPDATED_GOAL, FAILED_UPDATED_GOAL,
  DELETE_GOAL, CONFIRM_DELETE_GOAL, CANCEL_DELETE_GOAL, SEND_DELETED_GOAL, SUCCESSFUL_DELETED_GOAL, FAILED_DELETED_GOAL
}
