const REQUEST_PLAID_CREDS = 'REQUEST_PLAID_CREDS',
  RECEIVE_PLAID_CREDS = 'RECEIVE_PLAID_CREDS',
  FAILED_RECEIVED_PLAID_CREDS = 'FAILED_RECEIVED_PLAID_CREDS',
  CREATE_PLAID_LINK = 'CREATE_PLAID_LINK',
  LINK_NEW_ACCOUNT = 'LINK_NEW_ACCOUNT',
  REFRESH_PLAID_TOKEN = 'REFRESH_PLAID_TOKEN',
  FINISH_REFRESH = 'FINISH_REFRESH'


export {
    REQUEST_PLAID_CREDS,
    RECEIVE_PLAID_CREDS,
    FAILED_RECEIVED_PLAID_CREDS,
    CREATE_PLAID_LINK,
    LINK_NEW_ACCOUNT,
    REFRESH_PLAID_TOKEN,
    FINISH_REFRESH
}
