const CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  SEND_NEW_TRANSACTION = 'SEND_NEW_TRANSACTION',
  SUCCESSFUL_NEW_TRANSACTION = 'SUCCESSFUL_NEW_TRANSACTION',
  FAILED_NEW_TRANSACTION = 'FAILED_NEW_TRANSACTION',

  GET_TRANSACTIONS = 'GET_TRANSACTIONS',
  REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS',
  RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS',
  FAILED_RECEIVED_TRANSACTIONS = 'FAILED_RECEIVED_TRANSACTIONS',

  EDIT_TRANSACTION = 'EDIT_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  SEND_UPDATED_TRANSACTION = 'SEND_UPDATED_TRANSACTION',
  SUCCESSFUL_UPDATED_TRANSACTION = 'SUCCESSFUL_UPDATED_TRANSACTION',
  FAILED_UPDATED_TRANSACTION = 'FAILED_UPDATED_TRANSACTION',

  DELETE_TRANSACTION = 'DELETE_TRANSACTION',
  SEND_DELETED_TRANSACTION = 'SEND_DELETED_TRANSACTION',
  SUCCESSFUL_DELETED_TRANSACTION = 'SUCCESSFUL_DELETED_TRANSACTION',
  FAILED_DELETED_TRANSACTION = 'FAILED_DELETED_TRANSACTION'


export {
  CREATE_TRANSACTION, ADD_TRANSACTION, SEND_NEW_TRANSACTION, SUCCESSFUL_NEW_TRANSACTION, FAILED_NEW_TRANSACTION,
  GET_TRANSACTIONS, REQUEST_TRANSACTIONS, RECEIVE_TRANSACTIONS, FAILED_RECEIVED_TRANSACTIONS,
  EDIT_TRANSACTION, UPDATE_TRANSACTION, SEND_UPDATED_TRANSACTION, SUCCESSFUL_UPDATED_TRANSACTION, FAILED_UPDATED_TRANSACTION,
  DELETE_TRANSACTION, SEND_DELETED_TRANSACTION, SUCCESSFUL_DELETED_TRANSACTION, FAILED_DELETED_TRANSACTION
}
